---
- name: Provision VPS — базовая настройка
  hosts: vps
  become: yes
  vars_files:
    - group_vars/vps.yml
    - vault.yml
  roles:
    - common
    - docker
    - nginx

- name: Deploy LitiySew
  hosts: vps
  become: yes
  vars_files:
    - group_vars/vps.yml
    - vault.yml
  roles:
    - app
